// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa5h4t2MraI59b5NuPyt1DZbw_tHRu2fw',
    appId: '1:440752867637:web:556ce750fd89d731fae47c',
    messagingSenderId: '440752867637',
    projectId: 'fir-flutter-codelab-a2824',
    authDomain: 'fir-flutter-codelab-a2824.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-a2824.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6BIOYl4ONFy6rYnVmo9CqCXqnCfW_Yg0',
    appId: '1:440752867637:android:9ab3c71829971962fae47c',
    messagingSenderId: '440752867637',
    projectId: 'fir-flutter-codelab-a2824',
    storageBucket: 'fir-flutter-codelab-a2824.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArfXwxsVVLzsDL4cs1h8_3trQ-vb4BT-M',
    appId: '1:440752867637:ios:73f54613d85410eafae47c',
    messagingSenderId: '440752867637',
    projectId: 'fir-flutter-codelab-a2824',
    storageBucket: 'fir-flutter-codelab-a2824.appspot.com',
    iosClientId: '440752867637-dkcqu5sgqt3iplihc39b1s4e750fuk8k.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArfXwxsVVLzsDL4cs1h8_3trQ-vb4BT-M',
    appId: '1:440752867637:ios:73f54613d85410eafae47c',
    messagingSenderId: '440752867637',
    projectId: 'fir-flutter-codelab-a2824',
    storageBucket: 'fir-flutter-codelab-a2824.appspot.com',
    iosClientId: '440752867637-dkcqu5sgqt3iplihc39b1s4e750fuk8k.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
